import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import HeroLayout from "@/components/Layouts/HeroLayout";
import AboutLayout from "@/components/Layouts/AboutLayout";
import FooterLayout from "@/components/Layouts/FooterLayout";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>
          PT. Ryana Asta Jaya - merupakah perusahaan swasta yang bergerak dalam
          bidang Plastik & Packing.
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroLayout />
      <AboutLayout />
      <FooterLayout />
    </>
  );
}
